### ISSUE TITLE
Copy settings/channels from on Kodi install to another for the ytchannels plugin

### ISSUE THREAD

**Issue by wuster** [natko1412/repo.natko1412#1]
I'm a huge fan of the video.ytchannels plugin, but I can't figure out how to migrate all the great channels I found from a kodi install on one computer to another. I'm on Linux, and I already tried copying the ~/.kodi/userdata/addon_data/plugin.video.youtube.channels/ folder over to the new computer (after installing plugin.video.youtube.channels first). The plugin launches fine, but I don't see any of the custom channels from my original computer.

**Comment by natko1412** [comment]
You must copy folders.db file located in ~/.kodi/userdata/Database

**Comment by wuster** [comment]
Thanks, that worked perfectly. Once again, thanks for the great Kodi plugin.
